GET http://localhost:3000/orders
x-token: s11bjagfnt

###
GET http://localhost:3000/orders/99c03233-71b7-4fd6-bdf5-c72639b18ff4
x-token: s11bjagfnt

###
POST http://localhost:3000/orders
Content-Type: application/json
x-token: s11bjagfnt

{
    "id": "929ed3e0-e279-4757-9a5f-bd59185dac07",    
    "credit_card_number": "12345",
    "credit_card_name": "Leonel de Sousa",
    "amount": 30.30
}

###
POST http://localhost:3000/orders
Content-Type: application/json
x-token: s11bjagfnt

{    
    "id": "99c03233-71b7-4fd6-bdf5-c72639b18ff4",
    "credit_card_number": "5102497878839657",
    "credit_card_name": "Leonel de Sousa",
    "credit_card_expiration_month": 10,
    "credit_card_expiration_year": 2024,
    "credit_card_cvv": 122,
    "amount": 500
}

###
PATCH http://localhost:3000/orders/8d8bd4e7-6d4c-4714-baa5-36210d47bb53
Content-Type: application/json
x-token: s11bjagfnt

{
    "amount": 30.40,
    "credit_card_number": "12345678" 
}

###
DELETE http://localhost:3000/orders/99c03233-71b7-4fd6-bdf5-c72639b18ff4
x-token: s11bjagfnt