GET http://localhost:3000/accounts

###
GET http://localhost:3000/accounts/6da0fc7c-4c20-42f4-b9aa-3ad4aa0b043e

###
POST http://localhost:3000/accounts
Content-Type: application/json

{
    "name": "conta 3"
}

###
PATCH http://localhost:3000/accounts/6da0fc7c-4c20-42f4-b9aa-3ad4aa0b043e
Content-Type: application/json

{
    "name": "Conta 1"
}