GET http://localhost:3000/orders
x-token: wm9jhrn14l

###
GET http://localhost:3000/orders/da8f9397-a2d4-43ca-90f5-382829caf5b7
x-token: wm9jhrn14l

###
POST http://localhost:3000/orders
Content-Type: application/json
x-token: wm9jhrn14l

{
    "id": "99c03233-71b7-4fd6-bdf5-c72639b18ff4",    
    "credit_card_number": "12345",
    "credit_card_name": "Leonel de Sousa",
    "amount": 30.30
}

###
POST http://localhost:3000/orders
Content-Type: application/json
x-token: wm9jhrn14l

{    
    "id": "da8f9397-a2d4-43ca-90f5-382829caf5b7",
    "credit_card_number": "5102497878839657",
    "credit_card_name": "Leonel de Sousa",
    "credit_card_expiration_month": 10,
    "credit_card_expiration_year": 2024,
    "credit_card_cvv": 122,
    "amount": 500
}

###
PATCH http://localhost:3000/orders/8d8bd4e7-6d4c-4714-baa5-36210d47bb53
Content-Type: application/json
x-token: wm9jhrn14l

{
    "amount": 30.40,
    "credit_card_number": "12345678" 
}

###
DELETE http://localhost:3000/orders/99c03233-71b7-4fd6-bdf5-c72639b18ff4
x-token: wm9jhrn14l